# -*- coding: utf-8 -*-
"""customer

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-gCyTG9WCh9_0j_kQb1hRI0Tb9PMHk8w
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt


np.random.seed(42)

n = 100000

data = pd.DataFrame({
    "Customer_ID": np.arange(1, n+1),
    "Age": np.random.randint(18, 70, n),
    "Gender": np.random.choice(["Male", "Female"], n),
    "Tenure": np.random.randint(0, 11, n),
    "Balance": np.random.randint(0, 200000, n),
    "CreditScore": np.random.randint(300, 900, n),
    "EstimatedSalary": np.random.randint(10000, 150000, n),
    "NumOfProducts": np.random.randint(1, 5, n),
    "IsActiveMember": np.random.choice([0, 1], n),
    "Churn": np.random.choice([0, 1], n)
})

print(data.head())

print(data.isnull().sum())
print(data.dtypes)

print(data.describe())

print(data["Churn"].value_counts())

print(data.groupby("Age")["Churn"].mean())

data["Churn"].value_counts().plot(kind='bar')
plt.title("Churn Count")
plt.show()

plt.hist(data["Age"])
plt.title("Age Distribution")
plt.show()

plt.scatter(data["Balance"], data["Churn"])
plt.title("Balance vs Churn")
plt.show()

import seaborn as sns
sns.heatmap(data.corr(numeric_only=True), annot=True)
plt.show()